### ISSUE TITLE
Verificar o state CurrentUser do AccountContext.tsx pois está retornando undfined

### ISSUE THREAD

**Issue by denerbatista** [BiahLages/games#37]

**Comment by Malkavianson** [comment]
Em qual momento você encontrou esse problema, senão a aplicação inteira não estaria funcionando

**Comment by Malkavianson** [comment]
Coloca um pouco mais de detalhes sobre onde você encontrou o problema por gentileza

**Comment by denerbatista** [comment]
Deixei um console.log na page Settings verifica lá não retorna nada, tenta colocar um console.log lá no Accont Context antes de jogar pro state e um depois do state, antes funciona e depois não.
